# Generated by Django 4.0.3 on 2022-05-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_belong_lanmu_lanmu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='belong_lanmu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_lanmu', to='blog.lanmu'),
        ),
    ]
